const mascota = [
    {nombre: "Monica", edad: 3, tipo: "perro", peso: 12.5},
    {nombre: "Ana", edad: 4, tipo: "gato", peso: 14.5},
    {nombre: "Linda", edad: 5, tipo: "perico", peso: 15.5},
    {nombre: "lucas", edad: 2, tipo: "sapo", peso: 10.5},
    {nombre: "Lilo", edad: 1, tipo: "gallina", peso: 11.5},
    {nombre: "Akane", edad: 6, tipo: "culebra", peso: 16.5},
    {nombre: "Elizabet", edad: 2, tipo: "pantera rosa", peso: 124.5},
    {nombre: "Meliodas", edad: 3, tipo: "tucan", peso: 13.5},
    {nombre: "Ban", edad: 5, tipo: "elefante", peso: 400.5},
    {nombre: "Lina", edad: 9, tipo: "delfin", peso: 12.5},
    {nombre: "Cami", edad: 4, tipo: "lagarto", peso: 15.5},
    {nombre: "Viki", edad: 3, tipo: "lobo", peso: 14.5},
    {nombre: "Monrou", edad: 8, tipo: "alcon", peso: 11.5},
    {nombre: "Lord", edad: 7, tipo: "leon", peso: 28.5},
    {nombre: "Meyling", edad: 3, tipo: "pantera negra", peso: 129.5},
    {nombre: "Dani", edad: 6, tipo: "oso", peso: 11.5},
    {nombre: "Lina", edad: 8, tipo: "panda", peso: 11.5},
    {nombre: "Cami", edad: 7, tipo: "pantera blanca", peso: 111.5},
    {nombre: "Viki", edad: 3, tipo: "luciernaga", peso: 18.5},
    {nombre: "Monrou", edad: 2, tipo: "conejo", peso: 13.5},
    {nombre: "Lord", edad: 4, tipo: "rana", peso: 12.5},
    {nombre: "Meyling", edad: 6, tipo: "tortuga", peso: 11.56},
    {nombre: "Dani", edad: 7, tipo: "gabiota", peso: 16.5}
];
